# 高级索引

In [16]:
# https://numpy.org/devdocs/user/basics.indexing.html
import numpy as np

x = np.array([[1, 2], [3, 4], [5, 6]])
print(x, '\n')

# 注意(1)，(2)，(3)的索引区别
print(x[1, -1])  # (1)
print(x[(1, -1)], '\n')  # (1)的语法糖

print(x[[1, -1]])  #(2)

print(x[np.array([1, -1])])  #(3)

[[1 2]
 [3 4]
 [5 6]] 

4
4 

[[3 4]
 [5 6]]
[[3 4]
 [5 6]]


In [45]:
 # 案例来源：https://numpy.org/devdocs/user/basics.indexing.html
'''
# In this case, if the index arrays have a matching shape, 
# and there is an index array for each dimension of the array being indexed, the resultant array has the same shape as the index arrays, 
# and the values correspond to the index set for each position in the index arrays. 
# In this example, the first index value is 0 for both index arrays, and thus the first value of the resultant array is y[0, 0]. 
# The next value is y[2, 1], and the last is y[4, 2].
'''
y = np.arange(35).reshape(5, 7)
print(y, '\n')

print(y[np.array([0, 2, 4]), np.array([1, 1, 1])], '\n')
print(y[[0, 2, 4], 1], '\n')  # 利用广播机制
print(y[np.array([0, 2, 4]), 1], '\n')  # 利用广播机制

print(y[np.array([0, 2, 4])], '\n')
print(y[[0, 2, 4]])


[[ 0  1  2  3  4  5  6]
 [ 7  8  9 10 11 12 13]
 [14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27]
 [28 29 30 31 32 33 34]] 

[ 1 15 29] 

[ 1 15 29] 

[ 1 15 29] 

[[ 0  1  2  3  4  5  6]
 [14 15 16 17 18 19 20]
 [28 29 30 31 32 33 34]] 

[[ 0  1  2  3  4  5  6]
 [14 15 16 17 18 19 20]
 [28 29 30 31 32 33 34]]


# 字段访问